# Generated by Django 5.1.5 on 2025-02-23 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_questionsecond_choicesecond'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoiceSecond',
        ),
        migrations.DeleteModel(
            name='QuestionSecond',
        ),
    ]
